name: CI Test

on:
  push:
    branches: [main]

jobs:
  Frush-CDN:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run script
        run: |
          date -R  
          ls -a
          yarn
          node ./check-file-dir.js
